### ISSUE TITLE
Instance class db.t2.micro is incompatible with MySQL version 8

### ISSUE THREAD

**Issue by BradleyYeo** [hashicorp/learn-terraform-outputs#11]
│ Error: creating RDS DB Instance (terraform-20240325081656813800000004): InvalidParameterCombination: RDS does not support creating a DB instance with the following combination: DBInstanceClass=db.t2.micro, Engine=mysql, EngineVersion=8.0.35, LicenseModel=general-public-license. For supported combinations of instance class and database engine version, see the documentation.
│       status code: 400, request id: 9eddb874-accf-4a49-a851-eec4234470e5
│ 
│   with aws_db_instance.database,
│   on main.tf line 97, in resource "aws_db_instance" "database":
│   97: resource "aws_db_instance" "database" {

**Comment by BrianMMcClain** [comment]
Fixed by #12, thanks!
