### ISSUE TITLE
 Unsupported Terraform Core version

### ISSUE THREAD

**Issue by siemah** [hashicorp/learn-terraform-outputs#8]
I got this error when i try to initialize the terraform using `terraform init`

> Error: Unsupported Terraform Core version
│ 
│   on terraform.tf line 21, in terraform:
│   21:   required_version = "~> 1.2.0"
│ 
│ This configuration does not support Terraform
│ version 1.4.6. To proceed, either choose another
│ supported Terraform version or update this version
│ constraint. Version constraints are normally set for
│ good reason, so updating the constraint may lead to
│ other errors or unexpected behavior.

I am using **Terraform v1.4.6**. for that matter i think the `terraform` block need some updates especialy `required_version`
OS: macOS Big Sur version 11.7.7

**Comment by siemah** [comment]
I fixed this by updating the `required_version` from **1.2.0** to  **1.4.0**

**Comment by BrianMMcClain** [comment]
Thanks for the report! I'll marked this closed as this was just resolved by merging #10, thanks!
